version: "3.4"

services:
  sqlserver:
    container_name: sqlserver
    user: root
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Nova@Senha123Legal"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    restart: always
    volumes:
      - /webapi/src/Infra/Volumes/data:/var/opt/mssql/data
      - /webapi/src/Infra/Volumes/log:/var/opt/mssql/log
      - /webapi/src/Infra/Volumes/secrets:/var/opt/mssql/secrets
