version: '3.4'
services:
  sqlserver:
    container_name: sqlserver
    user: root
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Nova@Senha123Legal"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    restart: always
    
    #volumes:
      #- /APICatalogo/Infra/Volumes/data:/var/opt/mssql/data
      #- /APICatalogo/Infra/Volumes/log:/var/opt/mssql/log
      #- /APICatalogo/Infra/Volumes/secrets:/var/opt/mssql/secrets